spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:5432/onlineorder
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:Dsci-551}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: ${INIT_DB:never}
      schema-locations: "classpath:database-init.sql"

logging:
  level:
    # org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP requests
    # org.springframework.jdbc.datasource.init: DEBUG
    # org.springframework.jdbc.core: DEBUG # SQL