spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}:5432/onlineorder
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #      ddl-auto: create-drop  # dev
      ddl-auto: update
  sql:
    init:
      mode: ${INIT_DB:always}
      schema-locations: "classpath:database-init.sql"
  cache:
    caffeine:
      spec: expireAfterWrite=30m

#logging:
#  level:
    # org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP requests
    # org.springframework.jdbc.datasource.init: DEBUG
    # org.springframework.jdbc.core: DEBUG # SQL